apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sinks.loggie.io
spec:
  conversion:
    strategy: None
  group: loggie.io
  names:
    kind: Sink
    listKind: SinkList
    plural: sinks
    singular: sink
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines'
            type: string
          kind:
            description: 'Kind is a string value'
            type: string
          metadata:
            type: object
          spec:
            properties:
              sink:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
